[build]
builder = "NIXPACKS"
buildCommand = "cd /app && npm install --workspace=frontend && npm run build --workspace=frontend"

[deploy]
startCommand = "cd /app/frontend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

